apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: rr-blog-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: rr-blog
    spec:
      containers:
      - name: alpine-blog
        image: gcr.io/robren-blog-v1/alpine-blog:0.21.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always

